[project]
name = "analytics-service"
version = "0.1.0"
description = "FastAPI microservice"
requires-python = ">=3.12"
dependencies = [
    "nats-py>=2.10.2",
    "uvicorn>=0.40.0",
    "fastapi>=0.128.0",
]
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
